#!/bin/bash
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
colornow=$(cat /etc/rmbl/theme/color.conf)
colorfont=$(cat /etc/rmbl/warnafont/warnaf.conf)
NC="\e[0m"
RED="\033[0;31m"
COLOR1="$(cat /etc/rmbl/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
COLBG1="$(cat /etc/rmbl/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
export WH="$(cat /etc/rmbl/warnafont/$colorfont | grep -w "WARNAF" | cut -d: -f2|sed 's/ //g')"
y='\033[1;33m'
BGX="\033[42m"
CYAN="\033[96m"
z="\033[95;1m"
f="\033[1;97;41m"
G="\033[92m"
RED='\033[0;31m'
BRED='\033[1;31m'
NC='\033[0m'
gray="\e[1;30m"
Blue="\033[0;34m"
bblue="\033[1;34m"
green='\033[0;32m'
GREEN='\033[0;32m'
grenbo="\e[92;1m"
pr="\033[0;95m"
YELL='\033[0;33m'
orange='\033[33m'
mg='\033[35m'
white='\033[0;37m'
bwhite='\033[1;37m'
ipsaya=$(wget -qO- ifconfig.me)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/hamidw/permission/main/ip"
checking_sc() {
useexp=$(curl -sS $data_ip | grep $ipsaya | awk '{print $3}')
if [[ $date_list < $useexp ]]; then
echo -ne
else
echo -e "$COLOR1╭═════════════════════════════════════════════════╮${NC}"
echo -e "$COLOR1 ${NC} ${COLBG1}          ${WH}• AUTOSCRIPT PREMIUM •               ${NC} $COLOR1 $NC"
echo -e "$COLOR1╰═════════════════════════════════════════════════╯${NC}"
echo -e "$COLOR1╭═════════════════════════════════════════════════╮${NC}"
echo -e "$COLOR1│            ${RED}PERMISSION DENIED !${NC}                  │"
echo -e "$COLOR1│   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}           │"
echo -e "$COLOR1│     \033[0;33mBuy access permissions for scripts${NC}          │"
echo -e "$COLOR1│             \033[0;33mContact Your Admin ${NC}                 │"
echo -e "$COLOR1╰═════════════════════════════════════════════════╯${NC}"
exit
fi
}
checking_sc
author=$(cat /etc/profil)
clear
echo -e " $COLOR1╔════════════════════════════════════════════════════╗${NC}"
echo -e " $COLOR1║${NC}${COLBG1}                ${WH}• SSH PANEL MENU •                  ${NC}$COLOR1║ $NC"
echo -e " $COLOR1╚════════════════════════════════════════════════════╝${NC}"
echo -e " $COLOR1╔════════════════════════════════════════════════════╗${NC}"
echo -e " $COLOR1║$NC ${WH}[${COLOR1}01${WH}]$NC ${COLOR1}• ${WH}ADD AKUN          ${WH}[${COLOR1}08${WH}]$NC ${COLOR1}• ${WH}LIST MEMBER        $NC$COLOR1║$NC"
echo -e " $COLOR1║$NC ${WH}[${COLOR1}02${WH}]$NC ${COLOR1}• ${WH}TRIAL AKUN        ${WH}[${COLOR1}09${WH}]$NC ${COLOR1}• ${WH}LOCK AKUN USER$NC$COLOR1     ║$NC"
echo -e " $COLOR1║$NC ${WH}[${COLOR1}03${WH}]$NC ${COLOR1}• ${WH}RENEW AKUN        ${WH}[${COLOR1}10${WH}]$NC ${COLOR1}• ${WH}UNLOCK AKUN USER  $NC$COLOR1 ║$NC"
echo -e " $COLOR1║$NC ${WH}[${COLOR1}04${WH}]$NC ${COLOR1}• ${WH}DELETE AKUN       ${WH}[${COLOR1}11${WH}]$NC ${COLOR1}• ${WH}DELETE EXPIRED    $NC$COLOR1 ║$NC"
echo -e " $COLOR1║$NC ${WH}[${COLOR1}05${WH}]$NC ${COLOR1}• ${WH}CEK USER LOGIN    ${WH}[${COLOR1}12${WH}]$NC ${COLOR1}• ${WH}RESTORE AKUN       $NC$COLOR1║$NC"
echo -e " $COLOR1║$NC ${WH}[${COLOR1}06${WH}]$NC ${COLOR1}• ${WH}CEK USER CONFIG   ${WH}[${COLOR1}13${WH}]$NC ${COLOR1}• ${WH}LIMIT IP ON OFF $NC$COLOR1   ║$NC"
echo -e " $COLOR1║$NC ${WH}[${COLOR1}07${WH}]$NC ${COLOR1}• ${WH}CHANGE USER LIMIT ${WH}[${COLOR1}14${WH}]$NC ${COLOR1}• ${WH}AUTO KILL AKUN $NC$COLOR1    ║$NC"
echo -e " $COLOR1╚════════════════════════════════════════════════════╝${NC}"
echo -e " $COLOR1╔════════════════════════════════════════════════════╗${NC}"
echo -e " $COLOR1║$NC ${WH}[${COLOR1}15${WH}]$NC ${COLOR1}• ${WH}CEK LOGIN UDP     ${WH}                       $COLOR1   ║$NC"
echo -e " $COLOR1║$NC ${WH}[${COLOR1}16${WH}]$NC ${COLOR1}• ${WH}INSTALL UDP       ${WH}[${COLOR1}00${WH}]$NC ${COLOR1}• ${WH}EXIT          $NC$COLOR1     ║$NC"
echo -e " $COLOR1╚════════════════════════════════════════════════════╝${NC}"
echo -e " $COLOR1╔═════════════════════════ ${WH}BY${NC} ${COLOR1}═══════════════════════╗ ${NC}"
printf "                      ${COLOR1}%3s${NC} ${WH}%0s${NC} ${COLOR1}%3s${NC}\n" "• " "$author" " •"
echo -e " $COLOR1╚════════════════════════════════════════════════════╝${NC}"
echo -e ""
echo -ne " ${WH}Select menu ${COLOR1}: ${WH}"; read opt
case $opt in
01 | 1) clear ; add-ssh ; exit ;;
02 | 2) clear ; trial-ssh ; exit ;;
03 | 3) clear ; renew-ssh ; exit ;;
04 | 4) clear ; del-ssh ; exit ;;
05 | 5) clear ; ceklim ; exit ;;
06 | 6) clear ; user-ssh ; exit ;;
07 | 7) clear ; ganti-ip-ssh ; exit ;;
08 | 8) clear ; member-ssh ; exit ;;
09 | 9) clear ; lock ; exit ;;
10 | 10) clear ; unlock ; exit ;;
11 | 11) clear ; delexp ; exit ;;
12 | 12) clear ; recover ; exit ;;
13 | 13) clear ; Lt-on-off ; exit ;;
14 | 14) clear ; limitssh-ip ; exit ;;
15 | 15) clear ; cekudp; exit ;;
16 | 16)
clear
echo -e "${green} ANDA YAKIN UNTUK MEMASANG SCRIPT INI ? $NC"
echo -e "${green} MINIMAL RAM 2 GB BIAR DISK TIDAK FULL $NC"
echo -e "${green} OS SUPPORT UBUNTU 20.04 ONLY $NC"
echo -e ""
read -p "SUDAH LAPOR KE ADMIN ? [Y/N]:" arg
if [[ $arg == 'Y' ]]; then
  echo -e "${Blue}Tindakan Diteruskan! $NC"
  echo -e "${green}START. . . $NC"
elif [[ $arg == 'y' ]]; then
  echo -e "${Blue}Tindakan Diteruskan! $NC"
  clear
  echo -e "${Blue}START . . .$NC"
elif [[ $arg == 'N' ]]; then
  echo -e "${RED}Tindakan Dihentikan! $NC"
  sleep 1
  clear
  exit 0
elif [[ $arg == 'n' ]]; then
  echo -e "${RED}Tindakan Dihentikan! $NC"
  sleep 1
  clear
  rm -f /root/update.sh
  exit 0
else
  echo -e "${RED}Argumen Tidak Diketahui! $NC"
  sleep 1
  clear
  rm -f /root/update.sh
  exit 0
fi

##########
clear
wget https://raw.githubusercontent.com/hamidw/instalasi/main/files/udp-custom.sh && chmod +x udp-custom.sh && ./udp-custom.sh
;;
00 | 0) clear ; menu ; exit ;;
X  | 0) clear ; m-ssh ;;
x) exit ;;
*) echo "Anda salah tekan " ; sleep 1 ; m-ssh ;;
esac
